# Generated by Django 4.1.2 on 2022-11-24 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_users_credits_remove_users_expiry_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='date_of_birth',
        ),
    ]
