# Generated by Django 4.1.2 on 2022-11-25 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_users_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='api.question'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='right',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
