# Generated by Django 4.1.2 on 2022-11-26 04:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_answer_question_alter_answer_right'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionEssayUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('essay', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.essay')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='answer',
            name='essay',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='users',
        ),
        migrations.RemoveField(
            model_name='question',
            name='essay',
        ),
        migrations.DeleteModel(
            name='AnswerEssayUser',
        ),
        migrations.AddField(
            model_name='questionessayuser',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.question'),
        ),
        migrations.AddField(
            model_name='questionessayuser',
            name='users',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='question', through='api.QuestionEssayUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='essay',
            field=models.ManyToManyField(blank=True, related_name='question', through='api.QuestionEssayUser', to='api.essay'),
        ),
    ]
