# Generated by Django 4.1.2 on 2022-11-26 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_questionessayuser_remove_answer_essay_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionessayuser',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
