# Generated by Django 4.1.2 on 2022-11-26 05:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_questionessayuser_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerEssayUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.answer')),
                ('essay', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.essay')),
                ('users', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='question',
            name='users',
        ),
        migrations.RemoveField(
            model_name='question',
            name='essay',
        ),
        migrations.DeleteModel(
            name='QuestionEssayUser',
        ),
        migrations.AddField(
            model_name='answer',
            name='essay',
            field=models.ManyToManyField(blank=True, related_name='answer', through='api.AnswerEssayUser', to='api.essay'),
        ),
        migrations.AddField(
            model_name='answer',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='answer', through='api.AnswerEssayUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='essay',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question', to='api.essay'),
        ),
    ]
