# Generated by Django 4.1.7 on 2023-05-07 01:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_answeressayuser_remove_question_users_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='essay',
            new_name='essays',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='question',
            new_name='questions',
        ),
        migrations.RenameField(
            model_name='answeressayuser',
            old_name='answer',
            new_name='answers',
        ),
        migrations.RenameField(
            model_name='answeressayuser',
            old_name='essay',
            new_name='essays',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='essay',
            new_name='essays',
        ),
        migrations.AddField(
            model_name='answeressayuser',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='essay',
            name='is_custom',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='essay',
            name='time_essay',
            field=models.TimeField(blank=True, default=datetime.time(0, 40), null=True),
        ),
    ]
