# Generated by Django 4.1.7 on 2023-05-07 20:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rename_essay_answer_essays_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='essay',
            name='users',
        ),
        migrations.AddField(
            model_name='essay',
            name='users',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='essay', to=settings.AUTH_USER_MODEL),
        ),
    ]
