# Generated by Django 4.1.2 on 2023-05-17 17:14

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_rename_essays_answer_essay'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answeressayuser',
            name='date',
        ),
        migrations.AlterField(
            model_name='answeressayuser',
            name='answers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers_essay_user', to='api.answer'),
        ),
        migrations.AlterField(
            model_name='answeressayuser',
            name='essays',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers_essay_user', to='api.useressay'),
        ),
        migrations.AlterField(
            model_name='answeressayuser',
            name='users',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers_essay_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='essay',
            name='time_essay',
            field=models.DurationField(blank=True, choices=[(datetime.timedelta(seconds=1440), '24 minutos'), (datetime.timedelta(seconds=1920), '32 minutos'), (datetime.timedelta(seconds=2400), '40 minutos')], default='40 minutos', null=True),
        ),
        migrations.AlterField(
            model_name='useressay',
            name='essay',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_essay', to='api.essay'),
        ),
        migrations.AlterField(
            model_name='useressay',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='essay_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
