# Generated by Django 4.1.2 on 2023-05-17 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_answeressayuser_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='essay',
            name='time_essay',
        ),
        migrations.AddField(
            model_name='answeressayuser',
            name='time_essay',
            field=models.TextField(blank=True, null=True),
        ),
    ]
