# Generated by Django 4.1.2 on 2023-06-05 19:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_remove_essayanswer_essays_essayanswer_essay_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customessay',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='essay_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='answer',
            name='essay',
            field=models.ManyToManyField(blank=True, related_name='answer', through='api.AnswerEssayUser', to='api.customessay'),
        ),
        migrations.AlterField(
            model_name='answeressayuser',
            name='essays',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers_essay_user', to='api.customessay'),
        ),
        migrations.DeleteModel(
            name='UserEssay',
        ),
    ]
