# Generated by Django 4.2.1 on 2023-06-14 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_customessay_user_alter_answer_essay_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customessay',
            name='current_questions',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
